version: '3.9'
services:

  wolfstreamdb:
    build: 
      context: ./wolfstreamdb
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: WOLFSTREAMDB
      POSTGRES_USER: WOLFSTREAMUSER-DES
      POSTGRES_PASSWORD: WOLFSTREAMPASS-DES
    ports:
      - "5432:5432"
    networks:
      - desenv-network
    volumes: 
      - wolfstreamdb:/var/lib/postgresql
          
  redis-sever:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache-redis:/data
    networks:
      - desenv-network
      
  mongodb-server:
    image: mongo
    restart: always
    ports:
      - "27017:27017"    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root      
    networks:
      - desenv-network

volumes:
  cache-redis:
    driver: local
  wolfstreamdb:
    driver: local

networks:
  desenv-network:
    driver: bridge
  