version: '3.9'

services:

  jenkins:
    image: 'jenkins:2.60.3'
    container_name: jenkins
    user: root
    restart: always
    ports:
      - '18080:8080'
      - '15000:5000'
    volumes:
      - /home/huupv/data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - desenv-network
      
volumes:
  cache-redis:
    driver: local
  wolfstreamdb:
    driver: local
  mongodatadb:
    driver: local
  mongoconfigdb:
    driver: local
    

networks:
  desenv-network:
    driver: bridge  