version: '3.9'

services:

  jenkins:
    image: 'jenkins:2.60.3'
    container_name: jenkins
    user: root
    restart: always
    ports:
      - '18080:8080'
      - '15000:5000'
    environment:
      USER_ROOT: admin
      USER_PASS: admin@01
    volumes:
      - ./volume/var/jenkins_home:/var/jenkins_home
      - ./volume/var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  