--Tabela de Beneficicario
CREATE TABLE TbBeneficiario(
    CPF CHAR(11) NOT NULL PRIMARY KEY,
    NM_BENEFICIARIO VARCHAR(55) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL
);
CREATE INDEX TBBENEFI_NOME_INDEX ON TbBeneficiario (NM_BENEFICIARIO);