--Tabela de Pessoas
CREATE TABLE TbPerson(
    DOCUMENTID CHAR(20) NOT NULL PRIMARY KEY,
    NAME VARCHAR(55) NOT NULL,
    BIRTHDATE DATE NOT NULL
);
CREATE INDEX TbPersonIndx1 ON TbPerson (DOCUMENTID,NAME);

select * from TbPerson;